name: Build APK with Buildozer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip zip unzip openjdk-17-jdk build-essential libffi-dev libssl-dev libncurses5
        pip install --upgrade pip
        pip install buildozer cython
        mkdir -p ~/.android && echo '### User Agreements' > ~/.android/repositories.cfg
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d cmdline-tools
        mkdir -p $HOME/.buildozer/android/platform
        mv cmdline-tools $HOME/.buildozer/android/platform/cmdline-tools
        yes | $HOME/.buildozer/android/platform/cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform "platform-tools" "platforms;android-30" "build-tools;30.0.3"

    - name: Initialize buildozer (optional but safe)
      run: buildozer init || echo "Already initialized"

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: comanda-vocale-apk
        path: bin/*.apk
