name: Build APK with Buildozer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip zip unzip git openjdk-17-jdk build-essential libffi-dev libssl-dev libncurses5 libncurses5-dev libncursesw5 libncursesw5-dev
        pip install --upgrade pip
        pip install buildozer cython

    - name: Initialize buildozer (optional but safe)
      run: |
        buildozer init || echo "Already initialized"

    - name: Build APK
      run: buildozer android debug
      shell: bash

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: comanda-vocale-apk
        path: bin/*.apk
